spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: false

